config/routes.rb
Rails.application.routes.draw do
  root :to => 'entry#index'

  get '/entry/new',           to:'entry#new',    as:'new_entry'

  get '/entry/:id',           to:'entry#show',   as:'entry'

  get '/entry/edit/:id',      to:'entry#edit',   as:'edit_entry'

  post '/entry/create',       to:'entry#create', as:'create_entry'

  put '/entry/update/:id',    to:'entry#update', as:'update_entry'

  delete '/entry/destroy/:id',to:'entry#destroy', as:'destroy_entry'

  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.is_admin?
      can :access, :rails_admin   # grant access to rails_admin
      can :manage, :all           # allow superadmins to do anything
    end


    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :entries

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :category
  has_and_belongs_to_many :tags
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :entries
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entry_controller.rb
class EntryController < ApplicationController
  def index
    @entries = Entry.all
  end

  def show
    @entry = Entry.find(params[:id])

  end

  def new
    @entry = Entry.new
  end

  def edit
    @entry = Entry.find(params[:id])
    ##@category = Category.find(params[:'@entry.category_id'])カテゴリ名取りたいけどできん
  end

  def update
    entry = params.require(:entry).permit(:name, :entrybody, :category_id)
    entry = Entry.new(entry)
    if entry.save
       redirect_to entry
     else
       render :edit
     end
  end

  def destroy
    entry = Entry.find(params[:id])
    entry.destroy

    redirect_to root_path, notice: '削除されました'


  end

  def create
    entry = params.require(:entry).permit(:name, :entrybody, :category_id)
    entry = Entry.new(entry)
    if entry.save
      redirect_to entry
    else
      render :new
    end
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entry_helper.rb
module EntryHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/entry/edit.html.erb
<%= form_for @entry, :url => update_entry_path , :method => 'put' do |f| %>

   <div>
     <%= f.text_field :name %>
   </div>
   <div>
     <%= f.text_field :entrybody %>
   </div>
   <div class="field">
   カテゴリ<br>
   <%= f.collection_select :category_id, Category.all, :id, :name %>
   </div>
  <%= f.submit %>
<% end %>

<%= link_to '戻る', root_path %>

app/views/entry/index.html.erb
<table>
    <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.name %></td>
        <td><%= entry.entrybody %></rd>
        <td><%= link_to '詳細', entry %></td>
      </tr>
    <% end %>
    <tbody>
</table>
<p1><%= link_to '新規作成', new_entry_path %></p1>

app/views/entry/new.html.erb
<%= form_for @entry,:url => {:action => 'create'} do |f| %>

  <div class="field">
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.text_area :entrybody%>
  </div>

  <div class="field">
  カテゴリ<br>
  <%= f.collection_select :category_id, Category.all, :id, :name %>
  </div>
    <%= f.submit %>
  <% end %>

app/views/entry/show.html.erb
<p>
<strong>カテゴリ:</strong>
<%= @entry.category.name %>
</p>

<p>
<strong>Name:</strong>
<%= @entry.name %>
</p>

<p>
  <strong>本文:</strong>
  <%= @entry.entrybody %>
</p>
<%= link_to '戻る', root_path %>
<%= link_to '編集', edit_entry_path %>
<%= link_to '削除', destroy_entry_path, :method => 'delete', data: { confirm: '削除しますか?' } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sample2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

</body>
</html>

app/views/top/index.html.erb
<h1>TestBlog</h1>
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to "Settings", edit_user_registration_path, :class => "navbar-link" %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => "navbar-link" %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link' %>
<% end %>


<p>Find me in app/views/top/index.html.erb</p>